app: json2image
component: scf
inputs:
  description: This is a function in json2image-node application
  eip: false
  enableRoleAuth: true
  events:
    - apigw:
        name: scfjson2image
        parameters:
          endpoints:
            - function:
                functionQualifier: $DEFAULT
                isIntegratedResponse: true
              method: ANY
              path: /json2image
          environment: release
          protocols:
            - http
            - https
  handler: index.main_handler
  memorySize: 128
  name: json2image
  namespace: default
  publicAccess: true
  region: ap-guangzhou
  runtime: Nodejs12.16
  src: ./
  timeout: 3
name: ap-guangzhou_default_json2image
stage: dev
# When using this configuration file for deployment, make sure the file name is "serverless.yml".
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
